In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Definimos las dimensiones del modelo (Notación ISLP)
n = 5 # Número de observaciones (Usuarios)
p = 3 # Dimensionalidad (Features: Edad, Salario_USD, Engagement_Score)

# Construimos la Matriz X (n x p) con datos de juguete
X_matriz = np.array([
    [25, 3000, 8.5],  # Usuario 1: Vector en 3D
    [45, 8000, 4.2],  # Usuario 2
    [22, 1500, 9.8],  # Usuario 3
    [35, 5000, 6.1],  # Usuario 4
    [28, 4200, 7.5]   # Usuario 5
])

# Para comodidad humana, la envolvemos en un DataFrame
df_X = pd.DataFrame(X_matriz, columns=['Edad', 'Salario', 'Engagement'],
                    index=['U1', 'U2', 'U3', 'U4', 'U5'])

print("Nuestra Matriz Multidimensional X (n=5, p=3):")
display(df_X)

Nuestra Matriz Multidimensional X (n=5, p=3):

    Edad  Salario  Engagement
U1  25.0   3000.0         8.5
U2  45.0   8000.0         4.2
U3  22.0   1500.0         9.8
U4  35.0   5000.0         6.1
U5  28.0   4200.0         7.5

## Calculen y anoten la distancia euclidiana exacta entre el Usuario 2 y el Usuario 4.

In [19]:
u2 = df_X.loc['U2'].values
u4 = df_X.loc['U4'].values

d_numpy = np.linalg.norm(u2 - u4)
print(d_numpy)

3000.017268283634

Digamos que la distancia euclidiana es : 3000.01727
Esto es antes de poner la Estandarización Z-Score

## Apliquen una Estandarización Z-Score a toda la matriz usando código.

In [25]:
X_std = (X_matriz - X_matriz.mean(axis=0)) / X_matriz.std(axis=0)

df_X_std = pd.DataFrame(X_std, columns=df_X.columns, index=df_X.index)
display(df_X_std)
u2_Z = df_X_std.loc['U2'].values
u4_Z = df_X_std.loc['U4'].values
d_numpy_Z_Score = np.linalg.norm(u2_Z - u4_Z)
print(d_numpy_Z_Score)

        Edad   Salario  Engagement
U1 -0.729756 -0.615327    0.661024
U2  1.702765  1.680668   -1.559604
U3 -1.094635 -1.304125    1.332377
U4  0.486504  0.303071   -0.578396
U5 -0.364878 -0.064288    0.144599

2.083226483665642